// SHARCUpdate.hlsl — SHARC cache population pass.
//
// Sparse compute shader: for each kSparseBlockSize×kSparseBlockSize pixel block
// exactly one thread is selected to trace a diffuse path from the primary GBuffer
// surface.  Each hit is shaded with direct lighting and fed into the SHARC
// accumulation cache via SharcUpdateHit().  The path continues until
// SharcUpdateHit() returns false — either the path stack hits SHARC_PROPAGATION_DEPTH
// (2 with cache resampling, 4 without) or cache resampling terminates early.

// ---- SHARC defines (must precede SharcCommon.h) ----------------------------
#define SHARC_UPDATE                    1
#define SHARC_ENABLE_64_BIT_ATOMICS     1
#define HASH_GRID_ENABLE_64_BIT_ATOMICS 1

// ---- SHARC SDK headers -----------------------------------------------------
#include "SharcCommon.h"

// ---- Project headers --------------------------------------------------------
#include "RaytracingCommon.hlsli"
#include "CommonLighting.hlsli"
#include "Atmosphere.hlsli"

#include "srrhi/hlsl/SHARC.hlsli"

// ============================================================================
// Resource bindings (generated by srrhi from SHARCUpdateInputs)
// ============================================================================

static const srrhi::SHARCConstants g_Const = srrhi::SHARCUpdateInputs::GetConst();

static const Texture2D<float>    g_Depth     = srrhi::SHARCUpdateInputs::GetDepth();
static const Texture2D<float2>   g_Normals   = srrhi::SHARCUpdateInputs::GetNormals();
static const Texture2D<float4>   g_Albedo    = srrhi::SHARCUpdateInputs::GetAlbedo();
static const Texture2D<float2>   g_ORM       = srrhi::SHARCUpdateInputs::GetORM();

static RWStructuredBuffer<uint64_t>              g_HashEntries  = srrhi::SHARCUpdateInputs::GetHashEntries();
static RWStructuredBuffer<SharcAccumulationData> g_Accumulation = srrhi::SHARCUpdateInputs::GetAccumulation();
static RWStructuredBuffer<SharcPackedData>       g_Resolved     = srrhi::SHARCUpdateInputs::GetResolved();

static const RaytracingAccelerationStructure             g_SceneAS   = srrhi::SHARCUpdateInputs::GetSceneAS();
static const StructuredBuffer<srrhi::GPULight>           g_Lights    = srrhi::SHARCUpdateInputs::GetLights();
static const StructuredBuffer<srrhi::PerInstanceData>    g_Instances = srrhi::SHARCUpdateInputs::GetInstances();
static const StructuredBuffer<srrhi::MeshData>           g_MeshData  = srrhi::SHARCUpdateInputs::GetMeshData();
static const StructuredBuffer<srrhi::MaterialConstants>  g_Materials = srrhi::SHARCUpdateInputs::GetMaterials();
static const StructuredBuffer<srrhi::VertexQuantized>    g_Vertices  = srrhi::SHARCUpdateInputs::GetVertices();
static const StructuredBuffer<uint>                      g_Indices   = srrhi::SHARCUpdateInputs::GetIndices();

// ============================================================================
// Helpers
// ============================================================================

// Reconstruct world-space position from a GBuffer depth sample.
float3 ReconstructWorldPos(uint2 pixel, float depth)
{
    // NDC xy from pixel centre
    float2 uv      = (float2(pixel) + 0.5f) * g_Const.m_ViewportSizeInv;
    float2 clipXY  = uv * 2.0f - 1.0f;
    clipXY.y       = -clipXY.y;

    float4 worldH = MatrixMultiply(float4(clipXY, depth, 1.0f), g_Const.m_MatClipToWorld);
    return worldH.xyz / worldH.w;
}

// Shade a surface hit with all scene lights (direct lighting only, no IBL).
// Returns combined diffuse + specular radiance arriving at the hit point.
float3 EvaluateDirectLightingAtHit(
    float3 worldPos,
    float3 N,
    float3 V,
    float3 baseColor,
    float  roughness,
    float  metallic,
    inout RNG rng)
{
    LightingInputs inputs;
    inputs.N                = N;
    inputs.V                = V;
    inputs.L                = float3(0, 0, 0);
    inputs.worldPos         = worldPos;
    inputs.baseColor        = baseColor;
    inputs.roughness        = roughness;
    inputs.metallic         = metallic;
    inputs.ior              = 1.5f;
    inputs.radianceMipCount = 0;
    inputs.enableRTShadows  = true;
    inputs.sceneAS          = g_SceneAS;
    inputs.instances        = g_Instances;
    inputs.meshData         = g_MeshData;
    inputs.materials        = g_Materials;
    inputs.indices          = g_Indices;
    inputs.vertices         = g_Vertices;
    inputs.lights           = g_Lights;

    float3 p_atmo      = GetAtmospherePos(worldPos);
    inputs.sunRadiance = GetAtmosphereSunRadiance(p_atmo, g_Const.m_SunDirection, g_Lights[0].m_Intensity);
    inputs.sunDirection = g_Const.m_SunDirection;
    inputs.useSunRadiance = true;
    inputs.sunShadow    = 0.0f;

    PrepareLightingByproducts(inputs);

    LightingComponents direct = AccumulateDirectLighting(inputs, g_Const.m_LightCount, g_Const.m_CosSunAngularRadius, rng);
    return direct.diffuse + direct.specular;
}

// ============================================================================
// BuildSharcParameters — assembles the SharcParameters struct from hardcoded
// hash-grid defaults and the live camera position from the constant buffer.
// This avoids passing HashGridParameters through the cbuffer entirely; only
// the per-frame camera position (already in g_Const) is needed.
// ============================================================================
SharcParameters BuildSharcParameters()
{
    SharcParameters sharcParams;

    // Hash-grid tuning — hardcoded per SHARC defaults for typical scenes.
    sharcParams.hashGridParameters.cameraPosition = g_Const.m_CameraPosition;
    sharcParams.hashGridParameters.logarithmBase  = 2.0f;
    sharcParams.hashGridParameters.sceneScale     = 50.0f;
    sharcParams.hashGridParameters.levelBias      = 0.0f;

    sharcParams.hashGridData.capacity             = srrhi::SHARCConsts::SHARC_CACHE_ENTRIES;
    sharcParams.hashGridData.hashEntriesBuffer    = g_HashEntries;
    sharcParams.radianceScale                     = srrhi::SHARCConsts::RADIANCE_SCALE;
    sharcParams.accumulationBuffer                = g_Accumulation;
    sharcParams.resolvedBuffer                    = g_Resolved;

    return sharcParams;
}

// ============================================================================
// Compute shader entry point
// ============================================================================

[numthreads(8, 8, 1)]
void SHARCUpdate_CSMain(uint2 dispatchIdx : SV_DispatchThreadID)
{
    // ---- Sparse pixel selection ------------------------------------------------
    // Each kSparseBlockSize×kSparseBlockSize block contributes exactly one sample.
    // The selected pixel within the block is randomised per-block per-frame so
    // the cache receives uniform coverage over time.
    const uint blockSize = srrhi::SHARCConsts::SPARSE_BLOCK_SIZE;

    uint2 sparseBlock   = dispatchIdx / blockSize;
    uint2 offsetInBlock = dispatchIdx % blockSize;

    // Per-block random offset — use PCG hash of block coords XOR frame index
    uint hashX = PCGHash(sparseBlock.x ^ (sparseBlock.y << 16) ^ g_Const.m_FrameIndex);
    uint hashY = PCGHash(sparseBlock.y ^ (sparseBlock.x << 16) ^ (g_Const.m_FrameIndex + 1u));
    uint2 randomOffset = uint2(hashX % blockSize, hashY % blockSize);

    if (any(offsetInBlock != randomOffset))
        return;

    uint2 pixel = sparseBlock * blockSize + randomOffset;
    if (any(pixel >= g_Const.m_ViewportSize))
        return;

    // ---- GBuffer read ----------------------------------------------------------
    float depth = g_Depth[pixel];
    if (depth == 0.0f)
        return; // sky pixel — no surface to cache

    float3 worldPos  = ReconstructWorldPos(pixel, depth);
    float3 N         = DecodeNormal(g_Normals[pixel]);
    float2 orm       = g_ORM[pixel];
    float  roughness = orm.r;
    float  metallic  = orm.g;
    float4 albedo    = g_Albedo[pixel];
    float3 baseColor = albedo.rgb;

    // ---- Skip highly specular surfaces ----------------------------------------
    // SHARC caches diffuse-dominant indirect.  Mirror-like surfaces are handled
    // by the specular path in DeferredLighting and don't benefit from caching.
    if (roughness < srrhi::SHARCConsts::ROUGHNESS_THRESHOLD)
        return;

    // ---- Per-pixel RNG ---------------------------------------------------------
    RNG rng = InitRNG(pixel, g_Const.m_FrameIndex);

    // ---- Build SharcParameters -------------------------------------------------
    SharcParameters sharcParams = BuildSharcParameters();

    SharcState sharcState;
    SharcInit(sharcState);

    // ---- Trace path with signal back-propagation (SHARC loop) -----------------
    // Each iteration traces one segment.  SharcSetThroughput propagates the
    // segment throughput to all prior path vertices.  SharcUpdateHit returns
    // false when the path stack is full (SHARC_PROPAGATION_DEPTH reached) or
    // cache resampling terminates the path early.
    float3 surfPos   = worldPos;    // surface we're bouncing FROM
    float3 surfN     = N;
    float3 surfColor = baseColor;
    float  surfMetal = metallic;
    bool   firstHit  = true;        // first bounce uses SharcUpdateHit even on miss

    while (true)
    {
        float3 rayDir     = SampleHemisphereCosine(NextFloat2(rng), surfN);
        if (dot(surfN, rayDir) <= 0.0f) return;
        float3 throughput = surfColor * (1.0f - surfMetal);

        // Apply segment throughput to prior path vertices
        // (no-op on first bounce when pathLength == 0)
        SharcSetThroughput(sharcState, throughput);

        RayDesc ray;
        ray.Origin    = surfPos + surfN * 1e-3f;
        ray.Direction = rayDir;
        ray.TMin      = 1e-3f;
        ray.TMax      = 1e10f;

        RayHitInfo hitInfo;
        bool didHit = TraceRayStandard(ray, rng, hitInfo, g_SceneAS, g_Instances, g_MeshData, g_Materials, g_Indices, g_Vertices);

        if (!didHit)
        {
            float3 sky = GetAtmosphereSkyRadiance(surfPos, rayDir,
                            g_Const.m_SunDirection, g_Lights[0].m_Intensity,
                            /*bAddSunDisk=*/false);

            if (firstHit)
            {
                // First miss — create entry with sky radiance
                SharcHitData hd;
                hd.positionWorld = surfPos;
                hd.normalWorld   = surfN;
                SharcUpdateHit(sharcParams, sharcState, hd, sky, NextFloat(rng));
            }
            else
            {
                // Subsequent miss — propagate sky to prior vertices
                SharcUpdateMiss(sharcParams, sharcState, sky);
            }
            break;
        }

        // Extract surface attributes (same pattern as PathTracer)
        srrhi::PerInstanceData inst  = g_Instances[hitInfo.m_InstanceIndex];
        srrhi::MeshData        mesh  = g_MeshData[inst.m_MeshDataIndex];
        srrhi::MaterialConstants mat = g_Materials[inst.m_MaterialIndex];

        FullHitAttributes attr = GetFullHitAttributes(hitInfo, ray, inst, mesh, g_Indices, g_Vertices);
        PBRAttributes     pbr  = GetPBRAttributes(attr, mat);

        float3 geoN = normalize(attr.m_WorldNormal);
        float3 hitN  = getBentNormal(geoN, pbr.normal, ray.Direction);

        // Evaluate indirect radiance at the hit point
        float3 V  = -rayDir;
        float3 Li = EvaluateDirectLightingAtHit(
                        attr.m_WorldPos, hitN, V,
                        pbr.baseColor, pbr.roughness, pbr.metallic,
                        rng) + pbr.emissive;

        // Store at the surface we bounced FROM
        SharcHitData hd;
        hd.positionWorld = surfPos;
        hd.normalWorld   = surfN;

        if (!SharcUpdateHit(sharcParams, sharcState, hd, Li, NextFloat(rng)))
            break;

        // Advance to the hit surface for the next bounce
        surfPos   = attr.m_WorldPos;
        surfN     = hitN;
        surfColor = pbr.baseColor;
        surfMetal = pbr.metallic;
        firstHit  = false;
    }
}
