// SharcResolve.hlsl — SHARC cache resolve pass (temporal blending).
//
// Iterates over every cache entry and performs:
//   - Staleness eviction  (entries untouched for staleFrameNumMax frames are cleared)
//   - Temporal EMA blend  (blended = (N_old × old + N_new × new) / (N_old + N_new))
//   - Accumulation window clamping
//   - Clears the accumulation buffer for the next frame
//
// This pass is a thin wrapper around SharcResolveEntry() from the SHARC SDK.
// All algorithmic details (hash collision recovery, adjacent-level blending,
// firefly suppression, etc.) are handled opaquely inside the library.

// ---- SHARC SDK headers -----------------------------------------------------
#include "SharcCommon.h"

// ---- Project headers --------------------------------------------------------
#include "srrhi/hlsl/SHARC.hlsli"

// ============================================================================
// Resource bindings (generated by srrhi from SHARCResolveInputs)
// ============================================================================

static const srrhi::SHARCConstants g_Const = srrhi::SHARCResolveInputs::GetConst();

static RWStructuredBuffer<uint64_t>              u_HashEntries  = srrhi::SHARCResolveInputs::GetHashEntries();
static RWStructuredBuffer<SharcAccumulationData> u_Accumulation = srrhi::SHARCResolveInputs::GetAccumulation();
static RWStructuredBuffer<SharcPackedData>       u_Resolved     = srrhi::SHARCResolveInputs::GetResolved();

// ============================================================================
// Compute shader entry point
// ============================================================================

[numthreads(srrhi::SHARCConsts::LINEAR_BLOCK_SIZE, 1, 1)]
void SHARCResolve_CSMain(uint entryIndex : SV_DispatchThreadID)
{
    SharcParameters sharcParams;
    sharcParams.hashGridParameters.cameraPosition = g_Const.m_CameraPosition;
    sharcParams.hashGridParameters.logarithmBase  = srrhi::SHARCConsts::HASH_GRID_LOGARITHM_BASE;
    sharcParams.hashGridParameters.sceneScale     = srrhi::SHARCConsts::HASH_GRID_SCENE_SCALE;
    sharcParams.hashGridParameters.levelBias      = srrhi::SHARCConsts::HASH_GRID_LEVEL_BIAS;
    sharcParams.hashGridData.capacity             = srrhi::SHARCConsts::SHARC_CACHE_ENTRIES;
    sharcParams.hashGridData.hashEntriesBuffer    = u_HashEntries;
    sharcParams.accumulationBuffer                = u_Accumulation;
    sharcParams.resolvedBuffer                    = u_Resolved;
    sharcParams.radianceScale                     = srrhi::SHARCConsts::RADIANCE_SCALE;

    SharcResolveParameters resolveParams;
    resolveParams.cameraPositionPrev  = g_Const.m_CameraPositionPrev;
    resolveParams.accumulationFrameNum = srrhi::SHARCConsts::ACCUMULATION_FRAME_NUM;
    resolveParams.responsiveFrameNum  = srrhi::SHARCConsts::ACCUMULATION_FRAME_NUM; // mirror accumulation window
    resolveParams.staleFrameNumMax    = srrhi::SHARCConsts::STALE_FRAME_NUM_MAX;
    resolveParams.frameIndex          = g_Const.m_FrameIndex;

    SharcResolveEntry(entryIndex, sharcParams, resolveParams);
}
